apiVersion: v1
kind: Service
metadata:
  name: anthon-mongodb-service
  namespace: anthon-prod
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP