apiVersion: v1
kind: Secret
metadata:
  name: anthon-mongodb-secret
  namespace: anthon-prod
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: PLACEHOLDER
  MONGO_INITDB_ROOT_PASSWORD: PLACEHOLDER