version: '3.8'
name: anthon
services:
  anthon-postgres:
    image: postgres:15.3
    container_name: anthon-postgres
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: anthon
      POSTGRES_PASSWORD: anthon
      POSTGRES_DB: anthon
  anthon-mongodb:
    image: mongo:5.0.3
    container_name: anthon-mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./volumes/mongodb:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: anthon
        MONGO_INITDB_ROOT_PASSWORD: anthon
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  schema-registry:
      image: confluentinc/cp-schema-registry:latest
      hostname: schema-registry
      depends_on:
        - kafka-broker-1
      ports:
        - "8081:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
        SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_INTERNAL://localhost:19092
        SCHEMA_REGISTRY_DEBUG: 'true'
  kafka-broker-1:
      image: confluentinc/cp-kafka:latest
      hostname: kafka-broker-1
      ports:
        - "19092:19092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_INTERNAL://localhost:19092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  anthon-api:
    container_name: anthon-api
    build:
      context: ../services/anthon-api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgres://anthon:anthon@anthon-postgres:5432/anthon
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - anthon-postgres
  whisper-api:
    container_name: whisper-api
    build:
      context: ../services/whisper-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'
