version: '3.8'
name: anthon
services:
  anthon-postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: anthon
      POSTGRES_PASSWORD: anthon
      POSTGRES_DB: anthon
  anthon-api:
    container_name: anthon-api
    build:
      context: ../services/anthon-api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgres://anthon:anthon@anthon-postgres:5432/anthon
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - anthon-postgres
