name: anthon
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: anthon
      RABBITMQ_DEFAULT_PASS: anthon
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: anthon
      MONGO_INITDB_ROOT_PASSWORD: anthon
    volumes:
      - ./volumes/mongodb:/data/db
