version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: personal-mongodb
    volumes:
      - ./volumes/mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor