apiVersion: apps/v1
kind: Deployment
metadata:
  name: anthon-postgres-deployment
  namespace: anthon-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.10
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        envFrom:
          - secretRef:
              name: anthon-postgres-secret
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: anthon-postgres-pvc