apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anthon-postgres-pvc
  namespace: anthon-prod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi