apiVersion: v1
kind: Secret
metadata:
  name: anthon-postgres-secret
  namespace: anthon-prod
type: Opaque
stringData:
  POSTGRES_USER: PLACEHOLDER
  POSTGRES_PASSWORD: PLACEHOLDER
  POSTGRES_DB: PLACEHOLDER